/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const DietPlanLazyImport = createFileRoute('/dietPlan')()
const CalorieLazyImport = createFileRoute('/calorie')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const DietPlanLazyRoute = DietPlanLazyImport.update({
  path: '/dietPlan',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dietPlan.lazy').then((d) => d.Route))

const CalorieLazyRoute = CalorieLazyImport.update({
  path: '/calorie',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/calorie.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/calorie': {
      preLoaderRoute: typeof CalorieLazyImport
      parentRoute: typeof rootRoute
    }
    '/dietPlan': {
      preLoaderRoute: typeof DietPlanLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CalorieLazyRoute,
  DietPlanLazyRoute,
])

/* prettier-ignore-end */
